[tool.setuptools]
packages = ["code_as_data"]

[project]
name = "code-as-data"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.15.1",
    "annotated-types==0.7.0",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "fonttools==4.56.0",
    "iniconfig==2.1.0",
    "kiwisolver==1.4.8",
    "mako==1.3.9",
    "markupsafe==3.0.2",
    "matplotlib==3.10.1",
    "neo4j>=5.28.1",
    "networkx==3.4.2",
    "numpy==2.2.4",
    "packaging==24.2",
    "pillow==11.1.0",
    "pluggy==1.5.0",
    "psutil==7.0.0",
    "psycopg2-binary==2.9.10",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "pyparsing==3.2.1",
    "pytest==8.3.5",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "setuptools==77.0.1",
    "six==1.17.0",
    "sqlalchemy==2.0.39",
    "tqdm==4.67.1",
    "typing-extensions==4.12.2",
    "wheel>=0.45.1",
]
