name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux, aarch64-darwin, x86_64-darwin]
        isMain:
          - ${{ contains(github.ref, 'main') }}
        # Excluded emulated builds on PRs
        exclude:
          - system: aarch64-linux
            isMain: false
          - system: x86_64-darwin
            isMain: false
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Build all flake outputs
        run: |
          om ci run \
            --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} \
            --systems "${{ matrix.system }}" \
            --results=$HOME/omci.json \
            -- --accept-flake-config
